# This file was generated by GoReleaser. DO NOT EDIT.
class Diffy < Formula
  desc "Print colored diff more readable"
  homepage "https://github.com/ynqa/diffy/"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ynqa/diffy/releases/download/v0.1.1/diffy_0.1.1_darwin_amd64.tar.gz"
    sha256 "43346e4d3dd0e4c04edb0f88de23323c1f94eb663c52927c52a4a822396dada5"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/ynqa/diffy/releases/download/v0.1.1/diffy_0.1.1_linux_amd64.tar.gz"
      sha256 "4c24c7c49949f62b2d893f9499d60d5698facbb0bbcc0f1c755fd161675572be"
    end
  end

  def install
    bin.install "diffy"
  end
end
