# This file was generated by GoReleaser. DO NOT EDIT.
class Diffy < Formula
  desc "Print colored diff more readable"
  homepage "https://github.com/ynqa/diffy/"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ynqa/diffy/releases/download/v0.1.1/diffy_0.1.1_darwin_amd64.tar.gz"
    sha256 "2c1b64a0e03af32a3a93f211cc3342c682f16e9aab0f4e6c87e8f7cad050e396"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/ynqa/diffy/releases/download/v0.1.1/diffy_0.1.1_linux_amd64.tar.gz"
      sha256 "fcb5832990a893836c2f810536396c0bbba9af88facee9fbc9a12075ccc9b121"
    end
  end

  def install
    bin.install "diffy"
  end
end
