# This file was generated by GoReleaser. DO NOT EDIT.
class Diffy < Formula
  desc "Print colored diff more readable"
  homepage "https://github.com/ynqa/diffy/"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ynqa/diffy/releases/download/v0.1.0/diffy_0.1.0_darwin_amd64.tar.gz"
    sha256 "a68c0fbe1f2ea53aac269d4dbff06062a9f42faefcaebe5e4e3c611faf56facd"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/ynqa/diffy/releases/download/v0.1.0/diffy_0.1.0_linux_amd64.tar.gz"
      sha256 "f6771788bc53e022b8980326beb2516f5dfa0a07726e277fefa9e4617b4c7316"
    end
  end

  def install
    bin.install "diffy"
  end
end
