# This file was generated by GoReleaser. DO NOT EDIT.
class Ktop < Formula
  desc "A visualized monitoring dashboard for Kubernetes"
  homepage "https://github.com/ynqa/ktop/"
  version "0.1.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ynqa/ktop/releases/download/v0.1.2/ktop_0.1.2_darwin_amd64.tar.gz"
    sha256 "03e6bb7c070bd428b3a4e97577c8a912f49a9ff8011f8d6aa0950faba5c227d4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/ynqa/ktop/releases/download/v0.1.2/ktop_0.1.2_linux_amd64.tar.gz"
      sha256 "29e3af34c2e829d2e210270ed16a926ea57858939e202d4acccb77a5e3908484"
    end
  end

  def install
    bin.install "ktop"
  end
end
