# This file was generated by GoReleaser. DO NOT EDIT.
cask "grfnctl" do
  name "grfnctl"
  desc "Grafana CLI to manage dashboards, datasources, and snapshots."
  homepage "https://github.com/ynqa/grfnctl"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grfnctl"

  on_macos do
    on_intel do
      url "https://github.com/ynqa/grfnctl/releases/download/v#{version}/grfnctl_Darwin_x86_64.tar.gz",
        verified: "github.com/ynqa/grfnctl"
      sha256 "bcb188be8623111dc76bb5588d93ae7e59232dda3fe390a2db8469316b8fb044"
    end
    on_arm do
      url "https://github.com/ynqa/grfnctl/releases/download/v#{version}/grfnctl_Darwin_arm64.tar.gz",
        verified: "github.com/ynqa/grfnctl"
      sha256 "c3c4afa53a116265d947e63f54284e0578b2aee8ff63e6d91101e1c63dfb461f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ynqa/grfnctl/releases/download/v#{version}/grfnctl_Linux_x86_64.tar.gz",
        verified: "github.com/ynqa/grfnctl"
      sha256 "643ce22976eee69b887d98cf0f3229cf8117c182d1f3f1f9cda01910348ea8cc"
    end
    on_arm do
      url "https://github.com/ynqa/grfnctl/releases/download/v#{version}/grfnctl_Linux_arm64.tar.gz",
        verified: "github.com/ynqa/grfnctl"
      sha256 "1ad54e4519c6c00e0ec24ded30c975a793e03f900bf01ba42fdbb9da990a53bb"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grfnctl"]
    end
  end

  # No zap stanza required
end
